package practica1;
// Generated 24-feb-2025 22:39:36 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculos generated by hbm2java
 */
public class Vehiculos  implements java.io.Serializable {


     private int idVehiculo;
     private Contribuyente contribuyente;
     private Ordenanza ordenanza;
     private String tipo;
     private String marca;
     private String modelo;
     private String matricula;
     private String numeroBastidores;
     private Double caballosFiscales;
     private Double plazas;
     private Double centimetrosCubicos;
     private Double kgCarga;
     private Character exencion;
     private Date fechaMatriculacion;
     private Date fechaAlta;
     private Date fechaBajaTemporal;
     private Set reciboses = new HashSet(0);

    public Vehiculos() {
    }

	
    public Vehiculos(int idVehiculo, Contribuyente contribuyente, Ordenanza ordenanza, String tipo, String marca, String modelo, String matricula, String numeroBastidores, Date fechaMatriculacion, Date fechaAlta) {
        this.idVehiculo = idVehiculo;
        this.contribuyente = contribuyente;
        this.ordenanza = ordenanza;
        this.tipo = tipo;
        this.marca = marca;
        this.modelo = modelo;
        this.matricula = matricula;
        this.numeroBastidores = numeroBastidores;
        this.fechaMatriculacion = fechaMatriculacion;
        this.fechaAlta = fechaAlta;
    }
    public Vehiculos(int idVehiculo, Contribuyente contribuyente, Ordenanza ordenanza, String tipo, String marca, String modelo, String matricula, String numeroBastidores, Double caballosFiscales, Double plazas, Double centimetrosCubicos, Double kgCarga, Character exencion, Date fechaMatriculacion, Date fechaAlta, Date fechaBajaTemporal, Set reciboses) {
       this.idVehiculo = idVehiculo;
       this.contribuyente = contribuyente;
       this.ordenanza = ordenanza;
       this.tipo = tipo;
       this.marca = marca;
       this.modelo = modelo;
       this.matricula = matricula;
       this.numeroBastidores = numeroBastidores;
       this.caballosFiscales = caballosFiscales;
       this.plazas = plazas;
       this.centimetrosCubicos = centimetrosCubicos;
       this.kgCarga = kgCarga;
       this.exencion = exencion;
       this.fechaMatriculacion = fechaMatriculacion;
       this.fechaAlta = fechaAlta;
       this.fechaBajaTemporal = fechaBajaTemporal;
       this.reciboses = reciboses;
    }
   
    public int getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public Contribuyente getContribuyente() {
        return this.contribuyente;
    }
    
    public void setContribuyente(Contribuyente contribuyente) {
        this.contribuyente = contribuyente;
    }
    public Ordenanza getOrdenanza() {
        return this.ordenanza;
    }
    
    public void setOrdenanza(Ordenanza ordenanza) {
        this.ordenanza = ordenanza;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getNumeroBastidores() {
        return this.numeroBastidores;
    }
    
    public void setNumeroBastidores(String numeroBastidores) {
        this.numeroBastidores = numeroBastidores;
    }
    public Double getCaballosFiscales() {
        return this.caballosFiscales;
    }
    
    public void setCaballosFiscales(Double caballosFiscales) {
        this.caballosFiscales = caballosFiscales;
    }
    public Double getPlazas() {
        return this.plazas;
    }
    
    public void setPlazas(Double plazas) {
        this.plazas = plazas;
    }
    public Double getCentimetrosCubicos() {
        return this.centimetrosCubicos;
    }
    
    public void setCentimetrosCubicos(Double centimetrosCubicos) {
        this.centimetrosCubicos = centimetrosCubicos;
    }
    public Double getKgCarga() {
        return this.kgCarga;
    }
    
    public void setKgCarga(Double kgCarga) {
        this.kgCarga = kgCarga;
    }
    public Character getExencion() {
        return this.exencion;
    }
    
    public void setExencion(Character exencion) {
        this.exencion = exencion;
    }
    public Date getFechaMatriculacion() {
        return this.fechaMatriculacion;
    }
    
    public void setFechaMatriculacion(Date fechaMatriculacion) {
        this.fechaMatriculacion = fechaMatriculacion;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Date getFechaBajaTemporal() {
        return this.fechaBajaTemporal;
    }
    
    public void setFechaBajaTemporal(Date fechaBajaTemporal) {
        this.fechaBajaTemporal = fechaBajaTemporal;
    }
    public Set getReciboses() {
        return this.reciboses;
    }
    
    public void setReciboses(Set reciboses) {
        this.reciboses = reciboses;
    }




}


